name: walman
description: Open source wallet and password manager

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  animations: ^2.0.2
  barcode: ^2.2.1
  barcode_widget: ^2.0.2
  base32: ^2.1.1
  bip39: ^1.0.6
  cloud_firestore: ^3.1.16
  convert: ^3.0.2
  crypto: ^3.0.2
  cupertino_icons: ^1.0.4
  email_validator: ^2.0.1
  encrypt: ^5.0.1
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_redux: ^0.9.0
  flutter_secure_storage: ^5.0.2
  flutter_slidable: ^1.3.0
  freezed_annotation: ^1.1.0
  http: ^0.13.4
  json_annotation: ^4.5.0
  mobile_scanner: ^1.1.0
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.3
  uuid: ^3.0.6
  web3dart: ^2.3.5
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

dependency_overrides:
  analyzer: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - web3/build/BundleStorage_abi.json
    - .env
