@startuml passwords

skinparam actorStyle awesome

actor User as user

participant UI as ui

participant ActionStream as actions

participant Reducers as reducers

participant Epics as epics

participant "Secure Storage" as storage

== Create ==

user -> ui : completes the from\nand clicks create
ui -> actions : CreateNewPassword
actions -> reducers : CreateNewPassword
reducers -> reducers : update the state by adding\nthe new password
reducers -> ui : state updated
ui -> ui : update UI
actions -> epics : CreateNewPassword
epics -> actions : StoreBundleStart
actions -> epics : StoreBundleStart
epics -> storage : store the Bundle into the secure storage
alt #TECHNOLOGY store opration succeded
    epics -> actions : StoreBudnleSuccessful
else #LightSalmon store opration failed
    epics -> actions : StoreBundleFailed
end

...

@enduml