name: ci
on: [ push ]
jobs:
  check-flutter-code:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Update packages
        run: flutter pub get
      - name: Create mock .env
        run: |
          touch .env
      - name: Flutter format
        run: flutter format lib -l 120 --set-exit-if-changed
      - name: Flutter analyze
        run: flutter analyze
      - name: Unit Tests
        run: flutter test test/ut/lib/main.dart
  check-smart-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r web3/requirements.txt
          npm install -g prettier prettier-plugin-solidity
      - name: Check format (contracts)
        run: prettier --print-width 120 --check web3/contracts/**/*.sol
      - name: Check format (python script)
        run: black . --check --verbose
      - name: Build
        run: python3 web3/cscript.py build
